---
boxes:
  - name: Env
    session: []
    parties: ["*"]
    methods: 
      - name: main
        caller-parties: []
        caller-session: []
        async: true
      - name: handleAdv
        caller-parties: [corrupt adv]
        caller-session: [main]
        async: true

  - name: Pi Issuer
    session: [main]
    parties:
      - honest iss
    methods:
      - name: issueCred
        caller-parties: [iss]
        caller-session: []

  - name: Pi User
    session: [main]
    parties:
      - honest user
    methods:
      - name: receiveCred
        caller-parties: 
          - user
        caller-session: []

  - name: Channel
    session: [main, ch1]
    parties:
      - honest iss
      - corrupt iss
      - honest user
      - corrupt user
    methods:
      - name: send
        caller-parties: ["iss", "user"]
        caller-session: [main]
      - name: receive
        caller-parties: ["iss", "user"]
        caller-session: [main]

  - name: Adversary
    session: [main]
    parties:
      - corrupt iss
      - corrupt user
      - corrupt adv
    methods:
      - name: handleSend
        caller-parties: ["*"]
        caller-session: [main, ch1]
        async: true
      - name: handleEnvCommand
        caller-parties: [corrupt adv]
        caller-session: []
        async: false

settings:
  boxwidth: 10
  boxmargin: 1
  layerheight: 6
  showallarrows: false
