---
boxes:
  - name: Env
    session: []
    parties: ["*"]
    methods: 
      - name: main
        parties: []

  - name: Pi Issuer
    session: [main]
    parties:
      - honest iss
    methods:
      - name: issueCred
        parties: [honest iss]
        session: [main]

  - name: Pi User
    session: [main]
    parties:
      - honest user
    methods:
      - name: receiveCred
        parties: [honest user]
        session: [main]

  - name: Channel
    session: [main, ch1]
    parties:
      - honest iss
      - corrupt iss
      - honest user
      - corrupt user
    methods:
      - name: send
        parties: ["iss", "user"]
        session: [main,ch1]
      - name: receive
        parties: ["iss", "user"]
        session: [main,ch1]
    events:
      - name: onSend
        session: [main, ch1]
        handler: Adversary

  - name: Adversary
    session: [main]
    parties:
      - corrupt iss
      - corrupt user
      - corrupt adv
    methods:
      - name: handleEnvCommand
        parties: [corrupt adv]
    events:
      - name: relayToEnv
        session: [main]

settings:
  boxwidth: 7
  boxmargin: 1
  layerheight: 7
  showallarrows: false
