---
boxes:
  - name: Env
    session: []
    parties: ["*"]
    methods: 
      - name: main
        caller-parties: []
        caller-session: []
    handlers:
      - relayToEnv

  - name: Pi Issuer
    session: [main]
    parties:
      - honest iss
    methods:
      - name: issueCred
        caller-parties: [honest iss]
        session: [main]

  - name: Pi User
    session: [main]
    parties:
      - honest user
    methods:
      - name: receiveCred
        caller-parties: [honest user]
        session: [main]

  - name: Channel
    session: [main, ch1]
    parties:
      - honest iss
      - corrupt iss
      - honest user
      - corrupt user
    methods:
      - name: send
        caller-parties: ["iss", "user"]
        session: [main,ch1]
      - name: receive
        caller-parties: ["iss", "user"]
        session: [main,ch1]
    events:
      - name: onSend
        session: [main, ch1]

  - name: Adversary
    session: [main]
    parties:
      - corrupt iss
      - corrupt user
      - corrupt adv
    methods:
      - name: handleEnvCommand
        caller-parties: [corrupt adv]
    events:
      - name: relayToEnv
        session: [main]
    handlers:
      - onSend

settings:
  boxwidth: 10
  boxmargin: 1
  layerheight: 7
  showallarrows: false
